#:kivy 1.0

# Main Screen Box
BoxLayout:
    orientation: 'vertical'

    # Title Screen
    BoxLayout:
        orientation: 'horizontal'
        height: '20'
        Label:
            id:'Title'
            text: 'Ventilator Settings'
    
    # Main Settings
    BoxLayout:
        orientation: 'horizontal'
        Label:
            text: 'this on left'
        Label:
            text: 'this on middle'
        Label:
            text: 'this on right'
    
     # Subsection Settings
    BoxLayout:
        orientation: 'horizontal'
        Label:
            text: '1'
        Label:
            text: '2'
        Label:
            text: '3'
        Label:
            text: '4'